-- AlterTable
ALTER TABLE "User" ALTER COLUMN "post_test" SET DEFAULT '',
ALTER COLUMN "post_test" SET DATA TYPE TEXT,
ALTER COLUMN "pre_test" SET DEFAULT '',
ALTER COLUMN "pre_test" SET DATA TYPE TEXT,
ALTER COLUMN "username" DROP DEFAULT;
